import Link from 'next/link';
import { AppShell } from '@/components/AppShell';
import { getOperations, rel, money } from '@/lib/operations';

function reason(name:string,description=''){const text=(name+' '+description).toLowerCase();if(/fee|cost|financial/.test(text))return'Fees / financial';if(/location|distance|hostel/.test(text))return'Location / hostel';if(/competitor|joined/.test(text))return'Joined elsewhere';if(/wrong|invalid|duplicate/.test(text))return'Invalid / duplicate';if(/no response|unanswered/.test(text))return'No response';if(/not interested|drop|lost/.test(text))return'Not interested';return'Other / unspecified';}
export default async function LostPage(){const ops=await getOperations();const groups=new Map<string,{count:number,value:number}>();for(const lead of ops.dropped){const key=reason(rel(lead.stage_id,''),lead.description||'');const row=groups.get(key)||{count:0,value:0};row.count++;row.value+=lead.expected_revenue||0;groups.set(key,row);}const recoverable=ops.dropped.filter(l=>/no response|await|follow/i.test((rel(l.stage_id,'')+' '+(l.description||'')).toLowerCase())||((l.probability||0)>=30));return <AppShell active="/lost" title="Lost Lead Intelligence" subtitle="Understand why leads are dropping and recover the most valuable opportunities.">
<section className="grid compact-kpis"><div className="card"><div className="kpi-label">Dropped leads</div><div className="kpi-value">{ops.dropped.length}</div></div><div className="card"><div className="kpi-label">Recoverable</div><div className="kpi-value">{recoverable.length}</div></div><div className="card"><div className="kpi-label">Lost pipeline value</div><div className="kpi-value small-value">{money(ops.dropped.reduce((s,l)=>s+(l.expected_revenue||0),0))}</div></div><div className="card"><div className="kpi-label">Reason quality</div><div className="kpi-value">{ops.dropped.length?Math.round((ops.dropped.filter(l=>l.description).length/ops.dropped.length)*100):0}%</div><div className="kpi-note">Have descriptive context</div></div></section>
<section className="grid two"><div className="card"><div className="section-title">Drop reason analysis</div>{[...groups.entries()].sort((a,b)=>b[1].count-a[1].count).map(([name,row])=><div className="metric-row" key={name}><div><strong>{name}</strong><span>{row.count} leads</span></div><div className="bar"><span style={{width:`${Math.max(3,row.count/Math.max(ops.dropped.length,1)*100)}%`}}/></div><b>{money(row.value)}</b></div>)}</div><div className="card"><div className="section-title">Recovery playbook</div><p><strong>No response:</strong> create a fresh follow-up after results, scholarship announcements or admission deadlines.</p><p><strong>Fees:</strong> reopen when scholarships, instalments or revised packages become available.</p><p><strong>Location:</strong> pitch hostel, transport and day-boarding solutions.</p><p><strong>Joined elsewhere:</strong> retain for repeater, counselling or next academic-year campaigns.</p></div></section>
<section className="card table-card" style={{marginTop:16}}><div className="section-head"><div><div className="section-title">Recovery queue</div><div className="section-sub">Dropped leads with identifiable recovery potential.</div></div><span className="count-pill">{recoverable.length}</span></div><div className="table-scroll"><table><thead><tr><th>Lead</th><th>Reason</th><th>Owner</th><th>Probability</th><th>Value</th><th>Last update</th></tr></thead><tbody>{recoverable.slice(0,120).map(l=><tr key={l.id}><td><Link href={`/leads/${l.id}`}><strong>{l.name}</strong></Link></td><td>{reason(rel(l.stage_id,''),l.description||'')}</td><td>{rel(l.user_id)}</td><td>{l.probability||0}%</td><td>{money(l.expected_revenue)}</td><td>{l.write_date?.slice(0,16)}</td></tr>)}</tbody></table></div></section>
</AppShell>}
