import { unstable_cache } from 'next/cache';
import { AppShell } from '@/components/AppShell';
import { searchRead } from '@/lib/odoo';
import { inferGrade,inferInstitute,scoreLead,type ScorableLead } from '@/lib/scoring';

const load=unstable_cache(()=>searchRead<ScorableLead>('crm.lead',[['active','=',true]],['name','description','stage_id','user_id','team_id','probability','expected_revenue','write_date','activity_ids','phone','email_from','contact_name'],{limit:1200,order:'write_date desc'}),['segment-analysis-v1'],{revalidate:300});
type R={name:string;leads:number;confirmed:number;hot:number;pipeline:number;score:number};
function aggregate(leads:ScorableLead[], key:(l:ScorableLead)=>string):R[]{const m=new Map<string,{leads:number;confirmed:number;hot:number;pipeline:number;score:number}>();for(const l of leads){const k=key(l);const v=m.get(k)||{leads:0,confirmed:0,hot:0,pipeline:0,score:0};const s=scoreLead(l);v.leads++;v.confirmed+=Array.isArray(l.stage_id)&&l.stage_id[1].toLowerCase()==='admission confirmed'?1:0;v.hot+=s.score>=76?1:0;v.pipeline+=Number(l.expected_revenue||0);v.score+=s.score;m.set(k,v);}return [...m].map(([name,v])=>({name,...v,score:Math.round(v.score/v.leads)})).sort((a,b)=>b.leads-a.leads);}
const money=(n:number)=>`₹${n.toLocaleString('en-IN')}`;
export default async function SegmentsPage(){let leads:ScorableLead[]=[];let error='';try{leads=await load();}catch(e){error=e instanceof Error?e.message:'Unable to load segmentation';}
 const institutes=aggregate(leads,inferInstitute), grades=aggregate(leads,inferGrade), agents=aggregate(leads,l=>Array.isArray(l.user_id)?l.user_id[1]:'Unassigned');
 const Table=({title,rows}:{title:string;rows:R[]})=><section className="card table-card"><div className="section-head"><div><div className="section-title">{title}</div><div className="section-sub">Live leads, admissions, local score and pipeline value.</div></div></div><div className="table-scroll"><table><thead><tr><th>Segment</th><th>Leads</th><th>Admissions</th><th>Conversion</th><th>Hot</th><th>Avg score</th><th>Pipeline</th></tr></thead><tbody>{rows.map(r=><tr key={r.name}><td><strong>{r.name}</strong></td><td>{r.leads}</td><td>{r.confirmed}</td><td>{r.leads?((r.confirmed/r.leads)*100).toFixed(1):0}%</td><td>{r.hot}</td><td>{r.score}</td><td>{money(r.pipeline)}</td></tr>)}</tbody></table></div></section>;
 return <AppShell active="/segments" title="Institute, Grade & Sales Metrics" subtitle="Individual performance for every institute, inferred grade and salesperson from live Odoo leads.">{error?<div className="error-banner">{error}</div>:null}<div className="grid" style={{gap:16}}><Table title="Institute performance" rows={institutes}/><Table title="Grade performance" rows={grades}/><Table title="Salesperson performance" rows={agents}/></div><div className="card" style={{marginTop:16}}><div className="section-title">Classification note</div><div className="section-sub">Institute and grade are inferred from Odoo team, lead name and description when dedicated fields are unavailable. Once your exact custom Odoo field names are confirmed, these dimensions can switch to direct structured fields without changing the dashboard design.</div></div></AppShell>;
}