import { unstable_cache } from 'next/cache';
import { searchRead } from '@/lib/odoo';

type Rel = [number,string] | false;
type Lead = { id:number; name?:string; contact_name?:string; phone?:string; email_from?:string; stage_id?:Rel; user_id?:Rel; team_id?:Rel; source_id?:Rel; expected_revenue?:number; probability?:number; create_date?:string; write_date?:string; description?:string };
type Activity = { id:number; res_id:number; date_deadline?:string; user_id?:Rel; activity_type_id?:Rel; summary?:string; state?:string };
type Message = { id:number; res_id:number; date?:string; author_id?:Rel; body?:string; message_type?:string; subtype_id?:Rel };

const rel=(v:Rel|undefined)=>Array.isArray(v)?v[1]:'Unassigned';
const norm=(v:string)=>String(v||'').toLowerCase().replace(/<[^>]*>/g,' ').replace(/[^a-z0-9]+/g,' ').trim();
const daysSince=(v?:string)=>{const t=v?new Date(v).getTime():NaN;return Number.isFinite(t)?Math.max(0,Math.floor((Date.now()-t)/86400000)):999};
const money=(v=0)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v);

function stageBase(stage:string){const s=norm(stage); if(s.includes('admission confirmed')||s.includes('seat allotted'))return 100;if(s.includes('payment pending'))return 92;if(s.includes('entrance exam cleared'))return 80;if(s.includes('visited school'))return 64;if(s.includes('appointment scheduled'))return 56;if(s.includes('awaiting decision'))return 44;if(s.includes('3rd call'))return 38;if(s.includes('2nd call'))return 32;if(s.includes('1st call'))return 26;if(s.includes('new'))return 18;if(s.includes('unanswered'))return 10;if(/drop|reject|not interested|wrong lead|duplicate/.test(s))return 3;return 20}
function closed(stage:string){return /admission confirmed|seat allotted|drop|reject|not interested|wrong lead|duplicate|withdrawn/.test(norm(stage))}
function inferInstitute(lead:Lead){const text=norm(`${rel(lead.team_id)} ${lead.name} ${lead.description}`);if(text.includes('isc'))return "St. Mary's ISC";if(text.includes('smis')||text.includes('international'))return 'SMIS';if(text.includes('state board'))return 'State Board';if(text.includes('kids')||text.includes('pre primary')||text.includes('nursery'))return "St. Mary's Kids";return rel(lead.team_id)==='Unassigned'?'Unclassified':rel(lead.team_id)}
function inferGrade(lead:Lead){const text=norm(`${lead.name} ${lead.description}`);const m=text.match(/(?:grade|class|std|standard)\s*(\d{1,2})/);if(m)return `Grade ${m[1]}`;if(/11|12|neet|jee|science|commerce/.test(text))return 'Grade 11–12';if(/nursery|lkg|ukg|pre primary/.test(text))return 'Pre-primary';return 'Unclassified'}
function inferProgramme(lead:Lead){const t=norm(`${lead.name} ${lead.description}`);if(t.includes('neet long'))return 'NEET Long Term';if(t.includes('neet repeat'))return 'NEET Repeaters';if(t.includes('jee long'))return 'JEE Long Term';if(t.includes('jee repeat'))return 'JEE Repeaters';if(t.includes('neet'))return 'NEET';if(t.includes('jee'))return 'JEE';if(t.includes('commerce'))return 'Commerce';if(t.includes('science'))return 'Science';return 'General'}
function callKind(body:string){const t=norm(body);const confirmed=/call completed|spoke to|connected call|talked to|conversation with|called parent|called student/.test(t);const probable=/call|called|no answer|busy|switched off|ringing|not reachable|callback|follow up/.test(t);return confirmed?'confirmed':probable?'probable':'none'}
function lostReason(lead:Lead){const t=norm(`${rel(lead.stage_id)} ${lead.description}`);if(t.includes('fee')||t.includes('financial'))return 'Fees / financial';if(t.includes('distance')||t.includes('location'))return 'Location / distance';if(t.includes('competitor')||t.includes('joined'))return 'Joined elsewhere';if(t.includes('no response')||t.includes('unanswered'))return 'No response';if(t.includes('wrong lead')||t.includes('invalid'))return 'Invalid lead';if(t.includes('duplicate'))return 'Duplicate';if(t.includes('not interested'))return 'Not interested';return 'Reason not structured'}

export type AdvancedLead={id:number;name:string;contact:string;phone:string;stage:string;owner:string;institute:string;grade:string;programme:string;score:number;label:string;urgency:string;nextAction:string;flags:string[];revenue:number;updatedDays:number};
export type AdvancedSalesOS={kpis:{label:string;value:string;note:string}[];actions:AdvancedLead[];team:{name:string;leads:number;admissions:number;conversion:number;overdue:number;stagnant:number;confirmedCalls:number;probableCalls:number;score:number}[];segments:{kind:string;name:string;leads:number;admissions:number;hot:number;pipeline:number}[];stages:{name:string;count:number;value:number}[];lost:{reason:string;count:number}[];calls:{confirmed:number;probable:number;uniqueLeads:number;byAgent:{name:string;confirmed:number;probable:number;unique:number}[]};refreshedAt:string};

async function load():Promise<AdvancedSalesOS>{
 const today=new Date().toISOString().slice(0,10);const since=new Date(Date.now()-30*86400000).toISOString().slice(0,19).replace('T',' ');
 const leads=await searchRead<Lead>('crm.lead',[],['name','contact_name','phone','email_from','stage_id','user_id','team_id','source_id','expected_revenue','probability','create_date','write_date','description'],{limit:500,order:'write_date desc'});
 const activities=await searchRead<Activity>('mail.activity',[['res_model','=','crm.lead']],['res_id','date_deadline','user_id','activity_type_id','summary','state'],{limit:1000,order:'date_deadline asc'});
 let messages:Message[]=[];try{messages=await searchRead<Message>('mail.message',[['model','=','crm.lead'],['date','>=',since]],['res_id','date','author_id','body','message_type','subtype_id'],{limit:2500,order:'date desc'})}catch{}
 const activityMap=new Map<number,Activity[]>();for(const a of activities){const x=activityMap.get(a.res_id)||[];x.push(a);activityMap.set(a.res_id,x)}
 const messageMap=new Map<number,Message[]>();for(const m of messages){const x=messageMap.get(m.res_id)||[];x.push(m);messageMap.set(m.res_id,x)}
 const advanced:AdvancedLead[]=leads.map(l=>{const stage=rel(l.stage_id),age=daysSince(l.write_date),acts=activityMap.get(l.id)||[],msgs=messageMap.get(l.id)||[];const next=acts.filter(a=>a.date_deadline).sort((a,b)=>String(a.date_deadline).localeCompare(String(b.date_deadline)))[0];const overdue=Boolean(next?.date_deadline&&next.date_deadline<today&&!closed(stage));const noAction=!next&&!closed(stage);const comments=msgs.filter(m=>norm(m.body||'').length>8).length;let score=stageBase(stage)*.38+Math.max(0,Math.min(100,Number(l.probability||0)))*.22+(age<=1?100:age<=3?82:age<=7?58:age<=14?32:10)*.16+Math.min(100,acts.length*18+comments*7)*.12+(l.phone||l.email_from?70:10)*.06+Math.min(100,Number(l.expected_revenue||0)/10000)*.06;if(overdue)score-=10;if(noAction)score-=8;if(/drop|reject|wrong|duplicate/.test(norm(stage)))score-=20;score=Math.max(0,Math.min(100,Math.round(score)));const label=score>=78?'Hot':score>=60?'Warm':score>=42?'Develop':score>=25?'Cold':'Risk';const flags:string[]=[];if(overdue)flags.push('Overdue follow-up');if(noAction)flags.push('No next action');if(age>=7&&!closed(stage))flags.push(`${age} days stagnant`);if(!(l.phone||l.email_from))flags.push('Missing contact');if(rel(l.user_id)==='Unassigned')flags.push('Unassigned owner');const urgency=overdue||score>=82?'Critical':noAction||age>=7?'High':score>=60?'Medium':'Normal';const nextAction=overdue?'Complete overdue follow-up and record outcome':noAction?'Schedule a specific next action':age>=7?'Review blocker, add note and move stage':score>=78?'Call today and seek a decision date':'Continue planned follow-up';return{id:l.id,name:l.name||`Lead ${l.id}`,contact:l.contact_name||l.email_from||'—',phone:l.phone||'—',stage,owner:rel(l.user_id),institute:inferInstitute(l),grade:inferGrade(l),programme:inferProgramme(l),score,label,urgency,nextAction,flags,revenue:Number(l.expected_revenue||0),updatedDays:age}}).sort((a,b)=>{const u={Critical:4,High:3,Medium:2,Normal:1};return (u[b.urgency as keyof typeof u]-u[a.urgency as keyof typeof u])||b.score-a.score});
 const admissions=(l:Lead)=>/admission confirmed|seat allotted/.test(norm(rel(l.stage_id)));
 const byAgent=new Map<string,{leads:number;admissions:number;overdue:number;stagnant:number;confirmedCalls:number;probableCalls:number}>();for(const l of leads){const name=rel(l.user_id),row=byAgent.get(name)||{leads:0,admissions:0,overdue:0,stagnant:0,confirmedCalls:0,probableCalls:0};row.leads++;if(admissions(l))row.admissions++;const a=activityMap.get(l.id)||[];if(a.some(x=>x.date_deadline&&x.date_deadline<today))row.overdue++;if(daysSince(l.write_date)>=7&&!closed(rel(l.stage_id)))row.stagnant++;for(const m of messageMap.get(l.id)||[]){const k=callKind(m.body||'');if(k==='confirmed')row.confirmedCalls++;else if(k==='probable')row.probableCalls++}byAgent.set(name,row)}
 const team=[...byAgent].map(([name,r])=>{const conversion=r.leads?r.admissions/r.leads*100:0;const follow=Math.max(0,100-(r.overdue*2+r.stagnant));const activity=Math.min(100,r.confirmedCalls*5+r.probableCalls*2);const score=Math.round(conversion*.45+follow*.35+activity*.2);return{name,...r,conversion,score}}).sort((a,b)=>b.score-a.score);
 const seg=new Map<string,{kind:string;name:string;leads:number;admissions:number;hot:number;pipeline:number}>();for(const l of leads){const ad=advanced.find(x=>x.id===l.id)!;for(const [kind,name] of [['Institute',ad.institute],['Grade',ad.grade],['Programme',ad.programme]] as const){const key=`${kind}:${name}`,r=seg.get(key)||{kind,name,leads:0,admissions:0,hot:0,pipeline:0};r.leads++;if(admissions(l))r.admissions++;if(ad.score>=78)r.hot++;r.pipeline+=Number(l.expected_revenue||0);seg.set(key,r)}}
 const stageMap=new Map<string,{count:number;value:number}>(),lostMap=new Map<string,number>();for(const l of leads){const s=rel(l.stage_id),r=stageMap.get(s)||{count:0,value:0};r.count++;r.value+=Number(l.expected_revenue||0);stageMap.set(s,r);if(/drop|reject|not interested|wrong lead|duplicate|withdrawn/.test(norm(s)))lostMap.set(lostReason(l),(lostMap.get(lostReason(l))||0)+1)}
 const callAgent=new Map<string,{confirmed:number;probable:number;ids:Set<number>}>();let confirmed=0,probable=0;const unique=new Set<number>();for(const m of messages){const k=callKind(m.body||'');if(k==='none')continue;const name=rel(m.author_id),r=callAgent.get(name)||{confirmed:0,probable:0,ids:new Set<number>()};if(k==='confirmed'){confirmed++;r.confirmed++}else{probable++;r.probable++}unique.add(m.res_id);r.ids.add(m.res_id);callAgent.set(name,r)}
 const totalAdmissions=leads.filter(admissions).length,totalPipeline=leads.reduce((s,l)=>s+Number(l.expected_revenue||0),0),overdue=advanced.filter(x=>x.flags.includes('Overdue follow-up')).length,hot=advanced.filter(x=>x.score>=78).length;
 return{kpis:[{label:'Active leads',value:leads.length.toLocaleString('en-IN'),note:'Latest Odoo operational set'},{label:'Admissions',value:totalAdmissions.toLocaleString('en-IN'),note:`${leads.length?((totalAdmissions/leads.length)*100).toFixed(2):'0'}% conversion`},{label:'Hot leads',value:hot.toLocaleString('en-IN'),note:'Local score 78+'},{label:'Overdue',value:overdue.toLocaleString('en-IN'),note:'Immediate action queue'},{label:'Confirmed calls',value:confirmed.toLocaleString('en-IN'),note:'Strict note evidence'},{label:'Pipeline',value:money(totalPipeline),note:'Expected revenue'}],actions:advanced.slice(0,80),team,segments:[...seg.values()].sort((a,b)=>b.leads-a.leads),stages:[...stageMap].map(([name,r])=>({name,...r})).sort((a,b)=>b.count-a.count),lost:[...lostMap].map(([reason,count])=>({reason,count})).sort((a,b)=>b.count-a.count),calls:{confirmed,probable,uniqueLeads:unique.size,byAgent:[...callAgent].map(([name,r])=>({name,confirmed:r.confirmed,probable:r.probable,unique:r.ids.size})).sort((a,b)=>(b.confirmed+b.probable)-(a.confirmed+a.probable))},refreshedAt:new Date().toISOString()};
}
export const getAdvancedSalesOS=unstable_cache(load,['salesos-advanced-v1'],{revalidate:180,tags:['salesos-advanced']});
export {money};