import { AppShell } from '@/components/AppShell';
import { getOperationsAnalytics, money } from '@/lib/operations';

const targets=[['St. Mary’s ISC',120,82,9600000],['SMIS',180,109,7350000],['State Board',140,88,5280000],['St. Mary’s Kids',100,61,3050000]] as const;
export default async function TargetsPage(){const analytics=await getOperationsAnalytics();const pipeline=analytics.stages.reduce((s,x)=>s+x.value,0);return <AppShell active="/targets" title="Targets & Forecast" subtitle="Admissions and revenue targets with live pipeline forecasting.">
<section className="grid compact-kpis"><div className="card"><div className="kpi-label">Annual target</div><div className="kpi-value">540</div><div className="kpi-note">Across configured institutes</div></div><div className="card"><div className="kpi-label">Achieved</div><div className="kpi-value">340</div><div className="kpi-note">63% achievement</div></div><div className="card"><div className="kpi-label">Live pipeline</div><div className="kpi-value small-value">{money(pipeline)}</div><div className="kpi-note">Odoo expected revenue</div></div><div className="card"><div className="kpi-label">Weighted forecast</div><div className="kpi-value small-value">{money(pipeline*.42)}</div><div className="kpi-note">Baseline probability model</div></div></section>
<section className="card table-card"><div className="section-head"><div><div className="section-title">Institute target plan</div><div className="section-sub">Initial configurable target model. Live settings persistence comes next.</div></div></div><div className="table-scroll"><table><thead><tr><th>Institute</th><th>Target</th><th>Achieved</th><th>Remaining</th><th>Achievement</th><th>Revenue target</th><th>Status</th></tr></thead><tbody>{targets.map(([name,target,achieved,revenue])=>{const pct=Math.round(achieved/target*100);return <tr key={name}><td><strong>{name}</strong></td><td>{target}</td><td>{achieved}</td><td>{target-achieved}</td><td>{pct}%</td><td>{money(revenue)}</td><td><span className={`badge ${pct>=75?'good':pct<55?'hot':''}`}>{pct>=75?'On track':pct<55?'At risk':'Watch'}</span></td></tr>})}</tbody></table></div></section>
<section className="grid two"><div className="card"><div className="section-title">Forecast scenarios</div><div className="metric-row"><div><strong>Conservative</strong><span>25% of open pipeline</span></div><div className="bar"><span style={{width:'25%'}}/></div><b>{money(pipeline*.25)}</b></div><div className="metric-row"><div><strong>Expected</strong><span>42% weighted pipeline</span></div><div className="bar"><span style={{width:'42%'}}/></div><b>{money(pipeline*.42)}</b></div><div className="metric-row"><div><strong>Optimistic</strong><span>65% of open pipeline</span></div><div className="bar"><span style={{width:'65%'}}/></div><b>{money(pipeline*.65)}</b></div></div><div className="card"><div className="section-title">Required management actions</div><p>Prioritize overdue high-value leads, reduce stage ageing above seven days, and assign every active lead an open follow-up activity.</p><p className="cell-muted">The next target release will store targets by academic year, institute, grade, programme, month and salesperson.</p></div></section>
</AppShell>}
