import { unstable_cache } from 'next/cache';
import { AppShell } from '@/components/AppShell';
import { searchRead } from '@/lib/odoo';
import { inferGrade,inferInstitute,type ScorableLead } from '@/lib/scoring';

const instituteTargets:Record<string,number>={"St. Mary's ISC":120,SMIS:180,"St. Mary's State Board":140,"St. Mary's Kids":100,Unclassified:50};
const gradeTargets:Record<string,number>={'Grade 11–12':160,'Grade 10':70,'Grade 9':60,'Grade 8':55,'Grade 7':50,'Grade 6':45,'Grade 5':40,'Grade 1':70,'Pre-primary':100,Unclassified:80};
const load=unstable_cache(()=>searchRead<ScorableLead>('crm.lead',[['active','=',true]],['name','description','stage_id','team_id','expected_revenue'],{limit:1500}),['targets-live-v2'],{revalidate:300});
const money=(n:number)=>`₹${n.toLocaleString('en-IN')}`;
function rows(leads:ScorableLead[],key:(l:ScorableLead)=>string,targets:Record<string,number>){const m=new Map<string,{leads:number;won:number;pipeline:number}>();for(const l of leads){const k=key(l);const v=m.get(k)||{leads:0,won:0,pipeline:0};v.leads++;v.pipeline+=Number(l.expected_revenue||0);if(Array.isArray(l.stage_id)&&l.stage_id[1].toLowerCase()==='admission confirmed')v.won++;m.set(k,v);}return [...new Set([...Object.keys(targets),...m.keys()])].map(name=>({name,target:targets[name]||50,...(m.get(name)||{leads:0,won:0,pipeline:0})}));}
export default async function TargetsPage(){let leads:ScorableLead[]=[];let error='';try{leads=await load();}catch(e){error=e instanceof Error?e.message:'Unable to load targets';}const institutes=rows(leads,inferInstitute,instituteTargets),grades=rows(leads,inferGrade,gradeTargets);const totalTarget=institutes.reduce((s,r)=>s+r.target,0),achieved=institutes.reduce((s,r)=>s+r.won,0),pipeline=institutes.reduce((s,r)=>s+r.pipeline,0);
 const Table=({title,data}:{title:string;data:ReturnType<typeof rows>})=><section className="card table-card"><div className="section-head"><div><div className="section-title">{title}</div><div className="section-sub">Configured target versus live Admission Confirmed records.</div></div></div><div className="table-scroll"><table><thead><tr><th>Segment</th><th>Target</th><th>Active leads</th><th>Achieved</th><th>Remaining</th><th>Achievement</th><th>Pipeline</th><th>Status</th></tr></thead><tbody>{data.map(r=>{const p=Math.round(r.won/r.target*100);return <tr key={r.name}><td><strong>{r.name}</strong></td><td>{r.target}</td><td>{r.leads}</td><td>{r.won}</td><td>{Math.max(0,r.target-r.won)}</td><td>{p}%</td><td>{money(r.pipeline)}</td><td><span className={`badge ${p>=75?'good':p<40?'hot':''}`}>{p>=75?'On track':p<40?'At risk':'Watch'}</span></td></tr>})}</tbody></table></div></section>;
 return <AppShell active="/targets" title="Targets & Forecast" subtitle="Individual institute and grade targets with live sales pipeline metrics.">{error?<div className="error-banner">{error}</div>:null}<section className="grid compact-kpis"><div className="card"><div className="kpi-label">Institute target</div><div className="kpi-value">{totalTarget}</div><div className="kpi-note">Configured annual target</div></div><div className="card"><div className="kpi-label">Achieved</div><div className="kpi-value">{achieved}</div><div className="kpi-note">Admission Confirmed</div></div><div className="card"><div className="kpi-label">Live pipeline</div><div className="kpi-value small-value">{money(pipeline)}</div><div className="kpi-note">Expected revenue</div></div><div className="card"><div className="kpi-label">Local weighted forecast</div><div className="kpi-value small-value">{money(pipeline*.42)}</div><div className="kpi-note">Current baseline</div></div></section><div className="grid" style={{gap:16}}><Table title="Institute target plan" data={institutes}/><Table title="Grade target plan" data={grades}/></div><div className="card" style={{marginTop:16}}><div className="section-title">Target persistence</div><div className="section-sub">Targets are currently code-configured to avoid creating unapproved custom Odoo models. The permission-safe settings release can store targets by academic year, institute, grade, programme, month and salesperson after the exact storage location is approved.</div></div></AppShell>;
}